version: '3'

services:
  postgresql:
    build: ./postgres
    volumes:
      - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
  scrapers:
    build: .
    ports:
     - "8000:8000"
    volumes:
      - "./scrapers:/home/pupa/scrapers"
      - "./docker-libraries:/home/pupa/.local"
    depends_on:
     - postgresql