version: "3"

services:
  postgresql:
    build: ./postgres
    volumes:
      - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
  scrapers:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./scrapers:/home/pupa/scrapers"
    depends_on:
      - postgresql
  api:
    build: ./api
    ports:
      - "8002:8000"
    volumes:
      - "./api:/app"
      - "./site-packages-api:/home/pupa/.local/lib/python3.6/site-packages"
    depends_on:
      - postgresql
  councilmatic:
    build: ./sacramento-councilmatic
    ports:
      - "8001:8000"
    volumes:
      - "./sacramento-councilmatic:/home/pupa/councilmatic"
      - "./site-packages:/home/pupa/.local/lib/python3.7/site-packages"
    depends_on:
      - postgresql
