version: "3"

services:
  postgresql:
    build: ./postgres
    volumes:
      - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
  scrapers:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./scrapers:/home/pupa/scrapers"
    depends_on:
      - postgresql
  councilmatic:
    build: ./sacramento-councilmatic
    ports:
      - "8001:8000"
    volumes:
      - "./sacramento-councilmatic:/home/pupa/councilmatic"
    depends_on:
      - postgresql
